// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYysXnF9bYefl6iY2XkXY-5D7Mz1sjP10',
    appId: '1:533716313174:web:e83ecd416e1413fe78c7f7',
    messagingSenderId: '533716313174',
    projectId: 'paws-clinic',
    authDomain: 'paws-clinic.firebaseapp.com',
    storageBucket: 'paws-clinic.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa0xglYteWoJDZWHNoUnCApCJfSLuCyR0',
    appId: '1:533716313174:android:37d63636a83c80d078c7f7',
    messagingSenderId: '533716313174',
    projectId: 'paws-clinic',
    storageBucket: 'paws-clinic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsSOq41w2cqHlX9vHfFlUQCQye1XSFJAA',
    appId: '1:533716313174:ios:4241ffa9f093a72778c7f7',
    messagingSenderId: '533716313174',
    projectId: 'paws-clinic',
    storageBucket: 'paws-clinic.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsSOq41w2cqHlX9vHfFlUQCQye1XSFJAA',
    appId: '1:533716313174:ios:4241ffa9f093a72778c7f7',
    messagingSenderId: '533716313174',
    projectId: 'paws-clinic',
    storageBucket: 'paws-clinic.firebasestorage.app',
    iosBundleId: 'com.example.template',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYysXnF9bYefl6iY2XkXY-5D7Mz1sjP10',
    appId: '1:533716313174:web:17a931a81c60ad7778c7f7',
    messagingSenderId: '533716313174',
    projectId: 'paws-clinic',
    authDomain: 'paws-clinic.firebaseapp.com',
    storageBucket: 'paws-clinic.firebasestorage.app',
  );

}